

services:
  green-api-web:
    # Image for GitHub actions deploying
    image: ghcr.io/piecethelord/greenapiweb:latest
    container_name: green-api-frontend
    # Set volumes for our ssl certs to allow https connections
    volumes:
      - /etc/letsencrypt/live/alexey-web-dev.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/alexey-web-dev.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # 1. Point out the domen
      - "traefik.http.routers.oldapp.rule=Host(`greenapi.alexey-web-dev.ru`)"
      # 2. Get the Traffic by http
      # - "traefik.http.routers.oldapp.entrypoints=web"
      - "traefik.http.routers.oldapp.entrypoints=web,websecure" # Изменили web на websecure
      - "traefik.http.routers.oldapp.tls.certresolver=myresolver" # Сказали выпустить SSL!
      # 3. Point out to Traefik the port of our app
      - "traefik.http.services.oldapp.loadbalancer.server.port=80"

networks:
  web:
    external: true