server {
  listen 80;
  server_name greenapi.alexey-web-dev.ru _;
  # Redirect to https connection
  return 301 https://$host$request_uri;
}

server {
  # Open ssl port and set web site domain 
  listen 443 ssl;
  server_name greenapi.alexey-web-dev.ru _;

  # Set ssl certs path
  ssl_certificate /etc/nginx/ssl/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/privkey.pem;

  # Set ssl encryption version
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  # Set headers volume
  large_client_header_buffers 4 32k;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
  }
}