server {
  listen 80;
  server_name alexey-web-dev.ru www.alexey-web-dev.ru;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name alexey-web-dev.ru www.alexey-web-dev.ru;

  ssl_certificate /etc/nginx/ssl/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  large_client_header_buffers 4 32k;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
  }
}